version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: mongoose
    versions:
    - 5.11.16
    - 5.11.17
    - 5.11.19
    - 5.12.0
    - 5.12.1
    - 5.12.2
  - dependency-name: commander
    versions:
    - 7.1.0
